### ISSUE TITLE
Mocha stuck in loading and no test results get shown

### ISSUE THREAD

**Issue by sidrasultana** [mad-eye/leaderboard-mocha#6]
I followed http://www.meteortesting.com/chapter/velocity for adding mocha in new app. I am having trouble starting with mocha. I added the sample test files, but the html-reporter is stuck on loading the mocha files. The iFrame is empty, localhost:3000 is up and running though. Anything I can do? I had the same problem with jasmine.

Tried meteor update and VELOCITY_DEBUG=true meteor but the loading is still there with no progress.

**Comment by rissem** [comment]
Are you using this repo? I'm not too familiar with the testing manual, but this repo is deprecated and I'll probably delete it soon. I'd start from https://github.com/meteor-velocity/velocity-examples.
